name: E5 Bot
on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '12 */3 * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests
      run: |
        pip install -r requirements.txt
    - name: Read config from secrets
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_SECRET: ${{ secrets.CONFIG_SECRET }}
      run: | 
        echo $CONFIG_ID > client_id.txt
        echo $CONFIG_KEY > secret.txt
    - name: Test Api
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python api_bot.py
    - name: Delete secrets config
      run: | 
        rm -f client_id.txt
        rm -f secret.txt    
    - name: Commit # upload new refresh token
      run: |
        git config --global user.email windddk@163.com
        git config --global user.name windddk
        git add .
        git commit -m "update new refresh_token" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
