name: E5 Bot
on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test Api
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_SECRET: ${{ secrets.CONFIG_SECRET }}
        NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
      run: | 
        python api_bot.py
    - name: Commit and push # update new refresh token
      uses: matheusalbino/git-commit@v1.0.1
      with:
        user-name: tokenbot
        user-email: tokenbot@email.com
        message: update a refresh_token
        github-token: ${{ secrets.GITHUB_TOKEN }}
